# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swimming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimdate', models.CharField(max_length=100)),
                ('swimrange', models.IntegerField(default=0)),
                ('swimtime', models.IntegerField(default=0)),
                ('swimfeel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_type', models.CharField(max_length=100)),
                ('gym_sets', models.IntegerField(default=0)),
                ('gym_reps', models.IntegerField(default=0)),
            ],
        ),
    ]
