# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swimming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimrange', models.IntegerField(default=0)),
                ('swimtime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_type', models.CharField(max_length=100)),
                ('gym_sets', models.IntegerField(default=0)),
                ('gym_reps', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutDateNow', models.DateTimeField(auto_now_add=True)),
                ('workoutSport', models.CharField(max_length=100)),
                ('workoutFeel', models.CharField(max_length=100)),
                ('workoutUser', models.IntegerField()),
            ],
        ),
    ]
