# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagbok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutDate', models.CharField(max_length=100)),
                ('workoutRange', models.IntegerField(default=0)),
                ('workoutTime', models.IntegerField(default=0)),
                ('workoutFeel', models.CharField(max_length=100)),
            ],
        ),
    ]
