# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagbok', '0002_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='workoutSport',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
