# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagbok', '0004_auto_20160518_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='workoutDate',
            field=models.CharField(max_length=100),
        ),
    ]
