# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dagbok', '0006_workouts_workoutdatenow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='workoutDate',
        ),
    ]
